# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fuzzy_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 30, 101, 16))
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 60, 341, 341))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Data = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.Data.setGeometry(QtCore.QRect(0, 0, 341, 341))
        self.Data.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.Data.setObjectName("Data")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(390, 60, 341, 341))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 339, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Fmatrix = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.Fmatrix.setGeometry(QtCore.QRect(0, 0, 341, 341))
        self.Fmatrix.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.Fmatrix.setObjectName("Fmatrix")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(780, 60, 341, 341))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 339, 339))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.Result = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.Result.setGeometry(QtCore.QRect(0, 0, 341, 341))
        self.Result.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.Result.setObjectName("Result")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 440, 421, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 480, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Distance = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Distance.setContentsMargins(0, 0, 0, 0)
        self.Distance.setObjectName("Distance")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.Distance.addWidget(self.label_3)
        self.Euclidean = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Euclidean.setObjectName("Euclidean")
        self.Distance.addWidget(self.Euclidean)
        self.Cosine = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Cosine.setObjectName("Cosine")
        self.Distance.addWidget(self.Cosine)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 520, 361, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Compound = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Compound.setContentsMargins(0, 0, 0, 0)
        self.Compound.setObjectName("Compound")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.Compound.addWidget(self.label_4)
        self.MaxMinCom = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.MaxMinCom.setObjectName("MaxMinCom")
        self.Compound.addWidget(self.MaxMinCom)
        self.MaxDotPro = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.MaxDotPro.setObjectName("MaxDotPro")
        self.Compound.addWidget(self.MaxDotPro)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 560, 361, 89))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.Operation = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.Operation.setContentsMargins(0, 0, 0, 0)
        self.Operation.setObjectName("Operation")
        self.Process = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.Process.setObjectName("Process")
        self.Operation.addWidget(self.Process)
        self.Operation_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Operation_Button.setObjectName("Operation_Button")
        self.Operation.addWidget(self.Operation_Button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 670, 361, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.Clustring = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.Clustring.setContentsMargins(0, 0, 0, 0)
        self.Clustring.setObjectName("Clustring")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.Clustring.addWidget(self.label_7)
        self.Threshold = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.Threshold.setObjectName("Threshold")
        self.Clustring.addWidget(self.Threshold)
        self.Classification_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Classification_Button.setObjectName("Classification_Button")
        self.Clustring.addWidget(self.Classification_Button)
        self.MatPlot = QtWidgets.QWidget(self.centralwidget)
        self.MatPlot.setGeometry(QtCore.QRect(440, 470, 671, 221))
        self.MatPlot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MatPlot.setObjectName("MatPlot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fuzzy Clustring"))
        self.label.setText(_translate("MainWindow", "等价模糊矩阵"))
        self.label_2.setText(_translate("MainWindow", "数据"))
        self.label_5.setText(_translate("MainWindow", "分类结果"))
        self.label_6.setText(_translate("MainWindow", "分类变化散点图（x轴为分类阈值 y轴为分类数）"))
        self.label_3.setText(_translate("MainWindow", "距离选择"))
        self.Euclidean.setText(_translate("MainWindow", "欧式距离"))
        self.Cosine.setText(_translate("MainWindow", "三角余弦距离"))
        self.label_4.setText(_translate("MainWindow", "复合运算"))
        self.MaxMinCom.setText(_translate("MainWindow", "最大最小复合"))
        self.MaxDotPro.setText(_translate("MainWindow", "最大点积复合"))
        self.Process.setText(_translate("MainWindow", "显示复合运算过程"))
        self.Operation_Button.setText(_translate("MainWindow", "运算"))
        self.label_7.setText(_translate("MainWindow", "分类阈值(0-1)"))
        self.Classification_Button.setText(_translate("MainWindow", "分类"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))

